# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-04 19:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(default='blank', max_length=50)),
                ('last', models.CharField(default='blank', max_length=50)),
                ('alias', models.CharField(default='blank', max_length=50)),
                ('email', models.CharField(default='blank', max_length=255)),
                ('password', models.CharField(default='blank', max_length=255)),
                ('birthday', models.DateField(default='blank')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('friends', models.ManyToManyField(related_name='_user_friends_+', to='belt_app.User')),
            ],
        ),
        migrations.AddField(
            model_name='friend',
            name='friendee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendee', to='belt_app.User'),
        ),
        migrations.AddField(
            model_name='friend',
            name='friender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friender', to='belt_app.User'),
        ),
    ]
